### ISSUE TITLE
关于使用数据集token问题

### ISSUE THREAD

**Issue by Tust-nlp** [zhengzx-nlp/MGNMT#1]
我在yaml的配置文件中，数据集使用了不少tokenized，请问一下这个是怎么构建的呢？

**Comment by zhengzx-nlp** [comment]
Hi! 

tokenization 方面使用了 mosesdecoder 默认的 tokenizer，然后进行 bpe。

预处理流程可以参考:
https://github.com/pytorch/fairseq/blob/master/examples/translation/prepare-iwslt14.sh
https://github.com/pytorch/fairseq/blob/master/examples/translation/prepare-wmt14en2de.sh

祝好！
Zaixiang
